/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "C:\\Users\\林锦濠\\AppData\\Roaming\\npm\\node_modules\\vuepress\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-4d5b5468",
    path: "/exp/idea.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4d5b5468").then(next)
    },
  },
  {
    name: "v-acee48e6",
    path: "/about/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-acee48e6").then(next)
    },
  },
  {
    path: "/about/index.html",
    redirect: "/about/"
  },
  {
    name: "v-e2cdb85c",
    path: "/all/all.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e2cdb85c").then(next)
    },
  },
  {
    name: "v-f10fc648",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f10fc648").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-7cf7c3a6",
    path: "/exp/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7cf7c3a6").then(next)
    },
  },
  {
    path: "/exp/index.html",
    redirect: "/exp/"
  },
  {
    name: "v-494540b0",
    path: "/exp/training_order.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-494540b0").then(next)
    },
  },
  {
    name: "v-3b26e5d2",
    path: "/paper/paper.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3b26e5d2").then(next)
    },
  },
  {
    name: "v-02002172",
    path: "/paper/paper_writing.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-02002172").then(next)
    },
  },
  {
    name: "v-1c289d4f",
    path: "/paper/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1c289d4f").then(next)
    },
  },
  {
    path: "/paper/index.html",
    redirect: "/paper/"
  },
  {
    name: "v-246a7268",
    path: "/prepare4work/pre4work.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-246a7268").then(next)
    },
  },
  {
    name: "v-5dbb6f4f",
    path: "/reading/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5dbb6f4f").then(next)
    },
  },
  {
    path: "/reading/index.html",
    redirect: "/reading/"
  },
  {
    name: "v-0114a262",
    path: "/reading/insights.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0114a262").then(next)
    },
  },
  {
    name: "v-e3f3cb02",
    path: "/prepare4work/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e3f3cb02").then(next)
    },
  },
  {
    path: "/prepare4work/index.html",
    redirect: "/prepare4work/"
  },
  {
    name: "v-a5dc4468",
    path: "/tec/frontend/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a5dc4468").then(next)
    },
  },
  {
    path: "/tec/frontend/index.html",
    redirect: "/tec/frontend/"
  },
  {
    name: "v-55d9af7a",
    path: "/tec/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-55d9af7a").then(next)
    },
  },
  {
    path: "/tec/index.html",
    redirect: "/tec/"
  },
  {
    name: "v-15c1dbbf",
    path: "/tec/frontend/vue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-15c1dbbf").then(next)
    },
  },
  {
    name: "v-754b6726",
    path: "/tec/linux/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-754b6726").then(next)
    },
  },
  {
    path: "/tec/linux/index.html",
    redirect: "/tec/linux/"
  },
  {
    name: "v-75aa5265",
    path: "/tec/linux/linux.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-75aa5265").then(next)
    },
  },
  {
    name: "v-20e6f60a",
    path: "/tec/typora/grammar.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-20e6f60a").then(next)
    },
  },
  {
    name: "v-559a1e6c",
    path: "/tec/typora/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-559a1e6c").then(next)
    },
  },
  {
    path: "/tec/typora/index.html",
    redirect: "/tec/typora/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]