/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "ljh blog",
  "description": "welcomg to my blog",
  "base": "/myblog/",
  "headTags": [],
  "pages": [
    {
      "frontmatter": {},
      "regularPath": "/exp/idea.html",
      "relativePath": "exp/idea.md",
      "key": "v-4d5b5468",
      "path": "/exp/idea.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/about/",
      "relativePath": "about/README.md",
      "key": "v-acee48e6",
      "path": "/about/"
    },
    {
      "frontmatter": {},
      "regularPath": "/all/all.html",
      "relativePath": "all/all.md",
      "key": "v-e2cdb85c",
      "path": "/all/all.html"
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/hero.png",
        "actionText": "快速上手 →",
        "actionLink": "/all/all",
        "features": [
          {
            "title": "读书",
            "details": "书籍的力量"
          },
          {
            "title": "技术",
            "details": "码农的记录"
          },
          {
            "title": "生活",
            "details": "随笔随想"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2024-present ljh"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-f10fc648",
      "path": "/"
    },
    {
      "frontmatter": {},
      "regularPath": "/exp/",
      "relativePath": "exp/README.md",
      "key": "v-7cf7c3a6",
      "path": "/exp/"
    },
    {
      "title": "训练指令",
      "frontmatter": {},
      "regularPath": "/exp/training_order.html",
      "relativePath": "exp/training_order.md",
      "key": "v-494540b0",
      "path": "/exp/training_order.html",
      "headers": [
        {
          "level": 3,
          "title": "训练指令",
          "slug": "训练指令"
        },
        {
          "level": 3,
          "title": "可视化指令",
          "slug": "可视化指令"
        },
        {
          "level": 3,
          "title": "对齐操作",
          "slug": "对齐操作"
        },
        {
          "level": 3,
          "title": "自训练",
          "slug": "自训练"
        },
        {
          "level": 3,
          "title": "画图",
          "slug": "画图"
        }
      ]
    },
    {
      "title": "A Facial Expression-Aware Multimodal Multi-task Learning Framework for Emotion Recognition in Multi-party Conversations",
      "frontmatter": {},
      "regularPath": "/paper/paper.html",
      "relativePath": "paper/paper.md",
      "key": "v-3b26e5d2",
      "path": "/paper/paper.html",
      "headers": [
        {
          "level": 3,
          "title": "A Facial Expression-Aware Multimodal Multi-task Learning Framework for Emotion Recognition in Multi-party Conversations",
          "slug": "a-facial-expression-aware-multimodal-multi-task-learning-framework-for-emotion-recognition-in-multi-party-conversations"
        },
        {
          "level": 3,
          "title": "EMT_DLFR",
          "slug": "emt-dlfr"
        },
        {
          "level": 3,
          "title": "Robust-MSA",
          "slug": "robust-msa"
        },
        {
          "level": 3,
          "title": "NIAT",
          "slug": "niat"
        },
        {
          "level": 3,
          "title": "UniMF",
          "slug": "unimf"
        },
        {
          "level": 3,
          "title": "半监督的paper",
          "slug": "半监督的paper"
        },
        {
          "level": 3,
          "title": "my paper",
          "slug": "my-paper"
        },
        {
          "level": 3,
          "title": "meta_noise",
          "slug": "meta-noise"
        },
        {
          "level": 3,
          "title": "mask autoencoder",
          "slug": "mask-autoencoder"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/paper/paper_writing.html",
      "relativePath": "paper/paper_writing.md",
      "key": "v-02002172",
      "path": "/paper/paper_writing.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/paper/",
      "relativePath": "paper/README.md",
      "key": "v-1c289d4f",
      "path": "/paper/"
    },
    {
      "title": "*",
      "frontmatter": {},
      "regularPath": "/prepare4work/pre4work.html",
      "relativePath": "prepare4work/pre4work.md",
      "key": "v-246a7268",
      "path": "/prepare4work/pre4work.html",
      "headers": [
        {
          "level": 3,
          "title": "",
          "slug": ""
        },
        {
          "level": 3,
          "title": "idea",
          "slug": "idea"
        },
        {
          "level": 3,
          "title": "code",
          "slug": "code"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/reading/",
      "relativePath": "reading/README.md",
      "key": "v-5dbb6f4f",
      "path": "/reading/"
    },
    {
      "title": "语句摘抄",
      "frontmatter": {},
      "regularPath": "/reading/insights.html",
      "relativePath": "reading/insights.md",
      "key": "v-0114a262",
      "path": "/reading/insights.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/prepare4work/",
      "relativePath": "prepare4work/README.md",
      "key": "v-e3f3cb02",
      "path": "/prepare4work/"
    },
    {
      "frontmatter": {},
      "regularPath": "/tec/frontend/",
      "relativePath": "tec/frontend/README.md",
      "key": "v-a5dc4468",
      "path": "/tec/frontend/"
    },
    {
      "frontmatter": {},
      "regularPath": "/tec/",
      "relativePath": "tec/README.md",
      "key": "v-55d9af7a",
      "path": "/tec/"
    },
    {
      "frontmatter": {},
      "regularPath": "/tec/frontend/vue.html",
      "relativePath": "tec/frontend/vue.md",
      "key": "v-15c1dbbf",
      "path": "/tec/frontend/vue.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/tec/linux/",
      "relativePath": "tec/linux/README.md",
      "key": "v-754b6726",
      "path": "/tec/linux/"
    },
    {
      "title": "top",
      "frontmatter": {},
      "regularPath": "/tec/linux/linux.html",
      "relativePath": "tec/linux/linux.md",
      "key": "v-75aa5265",
      "path": "/tec/linux/linux.html",
      "headers": [
        {
          "level": 3,
          "title": "top",
          "slug": "top"
        },
        {
          "level": 3,
          "title": "tmux",
          "slug": "tmux"
        }
      ]
    },
    {
      "title": "Typosa快捷键",
      "frontmatter": {},
      "regularPath": "/tec/typora/grammar.html",
      "relativePath": "tec/typora/grammar.md",
      "key": "v-20e6f60a",
      "path": "/tec/typora/grammar.html",
      "headers": [
        {
          "level": 2,
          "title": "Typosa快捷键",
          "slug": "typosa快捷键"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/tec/typora/",
      "relativePath": "tec/typora/README.md",
      "key": "v-559a1e6c",
      "path": "/tec/typora/"
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "about",
        "link": "/about/about"
      },
      {
        "text": "Github",
        "link": "https://github.com/ChosenOne23"
      }
    ],
    "sidebar": [
      {
        "title": "技术",
        "path": "/tec/",
        "collapsable": true,
        "children": [
          {
            "title": "linux",
            "path": "/tec/linux/linux"
          },
          {
            "title": "frontend",
            "path": "/tec/frontend/vue"
          },
          {
            "title": "typora",
            "path": "/tec/typora/grammar"
          }
        ]
      },
      {
        "title": "实验",
        "path": "/exp/",
        "collapsable": true,
        "children": [
          {
            "title": "训练指令",
            "path": "/exp/training_order"
          },
          {
            "title": "想法",
            "path": "/exp/idea"
          }
        ]
      },
      {
        "title": "论文",
        "path": "/paper/",
        "collapsable": true,
        "children": [
          {
            "title": "阅读的相关文章",
            "path": "/paper/paper"
          },
          {
            "title": "文章的撰写",
            "path": "/paper/paper_writing"
          }
        ]
      },
      {
        "title": "prepare4work",
        "path": "/prepare4work/pre4work"
      },
      {
        "title": "阅读",
        "path": "/reading/insights"
      }
    ]
  }
}